/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as BilanRouteImport } from './routes/bilan'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as SaisieRouteImport } from './routes/saisie'
import { Route as TestsRouteImport } from './routes/tests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const BilanRoute = BilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieRoute = SaisieRouteImport.update({
  id: '/saisie',
  path: '/saisie',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/bilan': typeof BilanRoute
  '/resultats': typeof ResultatsRoute
  '/saisie': typeof SaisieRoute
  '/tests': typeof TestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/bilan': typeof BilanRoute
  '/resultats': typeof ResultatsRoute
  '/saisie': typeof SaisieRoute
  '/tests': typeof TestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/bilan': typeof BilanRoute
  '/resultats': typeof ResultatsRoute
  '/saisie': typeof SaisieRoute
  '/tests': typeof TestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/applications' | '/bilan' | '/resultats' | '/saisie' | '/tests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/applications' | '/bilan' | '/resultats' | '/saisie' | '/tests'
  id: '__root__' | '/' | '/applications' | '/bilan' | '/resultats' | '/saisie' | '/tests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BilanRoute: typeof BilanRoute
  ResultatsRoute: typeof ResultatsRoute
  SaisieRoute: typeof SaisieRoute
  TestsRoute: typeof TestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilan': {
      id: '/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof BilanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie': {
      id: '/saisie'
      path: '/saisie'
      fullPath: '/saisie'
      preLoaderRoute: typeof SaisieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  BilanRoute: BilanRoute,
  ResultatsRoute: ResultatsRoute,
  SaisieRoute: SaisieRoute,
  TestsRoute: TestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
